### ISSUE TITLE
invafetch failed to start on docker

### ISSUE THREAD

**Issue by Xtreme89** [geschke/grkopv-dashboard#1]
Hi,

erstmal Vielen Dank für die Mühe die Du dir hier gemacht hast!

Leider startet bei mir Invafetch im Docker-Container nicht so wirklich.

Docker-Compose wirft folgende Logs aus

```
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
invafetch_1  | exec ./invafetch: exec format error
```
Compose File sieht so aus

```
version: '3.7'
services:
  invafetch:
    image: geschke/invafetch:latest
    restart: always
    volumes:
      - ./invafetch/processdata.json:/app/processdata.json
    environment:
      DBHOST: "xxx"
      DBUSER: "solardbuser"
      DBNAME: "solardb"
      DBPASSWORD: "xxxx"
      DBPORT: "xx"
      INV_SERVER: "xx"
      INV_PASSWORD: "xx"
      INV_SCHEME: "https"
      #TIME_REQUEST_DURATION_SECONDS:2
      #TIME_NEW_LOGIN_MINUTES:1

```
das ganze läuft auf einem raspberry pi
Ideen?

Gruß
